### PR TITLE
Demo: save generated images

### PR DESCRIPTION
**Pull request by rubendax**
#### Changes:
- In the Gradio demo, generated images were not being saved. Now every generated image will be automatically saved to the directory `./outputs` as a `.png` file. The filename will be a timestamp with the format: `<year>_<month>_<day>-<hour>_<minute>_<second>.png`
- Edited some spelling and grammar in the Gradio demo description to help with clarity.

Tested these changes on a Linux machine with A6000 GPU.

#### EDIT 2024-11-05:
- Automatic image saving can be toggled on or off via a checkbox in the user interface.

### CODE REVIEW

**Comment by staoxiao** [comment]
Thank you for your contribution. However, I'm not sure if users want to save all the images.

**Comment by rubendax** [comment]
That's fair. To be honest, when I first tried the Gradio demo, I did not see any way to download the generated image in the interface, which is why I added this. I see now that it is possible to download an image by clicking in the upper right corner of the generated image in the UI. Many image generation apps do save all generated images by default, but this is a preference, rather than a necessary feature.

I have commented out the automatic image saving in this PR, just in case you want to incorporate my spelling/grammar edits.

Thanks so much for your work on this incredible project. OmniGen is truly a paradigm shift in image generation.

**Comment by vootox** [comment]
Thank you rubendax, I'd been searching specifically for how to enable this ability and found it here.

I appreciate the ability to save to a folder of choice, downloading each time to the browser's default download folder was becoming cluttered. Although the PNG files are much larger, having this convenience is worth the option for me.

Also, since I didn't know how to use GitHub correctly to use the 'branch' I manually swapped app.py for this pull request to my installation. My guess is that's not the way to do it!

As a hobbyist, OmniGen is already a much-appreciated part of my toolkit; this is only my 2nd day of using it.

**Comment by rubendax** [comment]
@vootox You should clone my branch called [demo-save_outputs](https://github.com/rubendax/OmniGen/tree/demo-save_outputs). This has the auto-saving functionality enabled and is otherwise up-to-date with all the improvements from upstream VectorSpaceLab:main (at least as of today 2024-11-05).
```
git clone -b demo-save_outputs https://github.com/rubendax/OmniGen
```

**Comment by rubendax** [comment]
@staoxiao I have added a checkbox to the UI to allow the user to toggle on or off saving all generated images as .png files to `./outputs`. In this branch, rubendax:main, this functionality is toggled **off** (unchecked) by default.
save_generated_images

**Comment by vootox** [comment]
> @vootox You should clone my branch called [demo-save_outputs](https://github.com/rubendax/OmniGen/tree/demo-save_outputs). This has the auto-saving functionality enabled and is otherwise up-to-date with all the improvements from upstream VectorSpaceLab:main (at least as of today 2024-11-05).
> 
> ```
> git clone -b demo-save_outputs https://github.com/rubendax/OmniGen
> ```

Thank you @rubendax, I have this installed and running, I like this a lot. Now, I'm wondering if there could be a script for batch processing images... just kidding, but it would be nice!

**Pull request merged**
